### ISSUE TITLE
Multiple warnings for tasks still running on D127579

### ISSUE THREAD

**Issue by ahal** [mozilla/code-review#1003]
Screenshot:
![image](https://user-images.githubusercontent.com/273734/136416002-89fdab83-334a-44ec-b04c-e04d5efdefe7.png)

[Phabricator revision](https://phabricator.services.mozilla.com/D127579)

Also the tasks in CI appear to have been competed. Andi notes that this is happening in the `ci/taskgraph` repo and likely happening because we don't report any tasks to reviewbot there.

**Comment by marco-c** [comment]
@abpostelnicu could you take this?
