### ISSUE TITLE
Report which clang checks are used 

### ISSUE THREAD

**Issue by La0** [mozilla/code-review#12]
On each analysis we can easily report the clang checks found in issues on Datadog.
That would give use basic stats over custom period of times.

To get an HTML output with links to the relevant bugs/reviews, would imply:
1. a Python script listing the N last tasks from the Taskcluster index,
2. that downloads the json report for each task,
3. Aggregates the data,
4. Outputs an html file

This could then be automated through a Taskcluser hook with a schedule.

**Comment by marco-c** [comment]
Do we have this in the new frontend?

**Comment by La0** [comment]
Yes, on [the stats page](https://code-review.moz.tools/#/stats), by filtering the analyzers down to `source-test-clang-tidy`
