### ISSUE TITLE
Support other projects (not mozilla-central)

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-review#13]
Over in https://bugzilla.mozilla.org/show_bug.cgi?id=1490082, Dustin requested linting checks to be run on ci-admin (https://hg.mozilla.org/build/ci-admin/), which is a separate project from mozilla-central.
We should figure out how we can support this use case, there are other projects too that we could support (e.g. NSS or Lando itself, see #1510).

**Comment by La0** [comment]
Doing exactly that in #461 !
