### ISSUE TITLE
Consider overriding push author too

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-review#133]
See discussion in #101.

**Comment by La0** [comment]
I don't think that's possible, as the push author is derived from the ssh key used to push.

**Comment by La0** [comment]
On [that line in mozilla/treeherder](https://github.com/mozilla/treeherder/blob/b621781f2606000bac3693eb324e8e565728682c/treeherder/etl/push.py#L22), we see that a push author is the [push user](https://github.com/mozilla/treeherder/blob/4704764a896417c58e9cc3daf97bcdebb2f33b72/treeherder/etl/pushlog.py#L48) from pushlog

**Comment by La0** [comment]
I made a patch to treeherder to do the opposite and allow filtering pushes by their commit's author.

**Comment by marco-c** [comment]
> I made a patch to treeherder to do the opposite and allow filtering pushes by their commit's author.

Nice, so we can close this (we weren't sure we wanted to do it because of its cons, but if there is a separate filter that's much better).
