### ISSUE TITLE
Check ingestion of autoland & mozilla-central warnings

### ISSUE THREAD

**Issue by La0** [mozilla/code-review#1427]
As we now produce a lot of warnings on autoland and mozilla-central runs, we should see a lot of issues being created on the backend, but that's not the case.

Revisions keep being ingested, but the issues count stays relatively low (probably a filter on the warning level somewhere).

**Comment by La0** [comment]
We looked into this with @vrigal :
- we need to add `integration/autoland` to the list of repositories with soft warnings (as we only support try & MC right now).
- issues on mozilla central are produced, but not ingested, we need to:
   1. support mozilla-central pulse messages in events (see #1435)
   2. support ingestion from mozilla-central in the bot code (see #1436)

**Comment by vrigal** [comment]
Done with  #1435 and #1436
