### ISSUE TITLE
Backend admin panel listing issues fails

### ISSUE THREAD

**Issue by La0** [mozilla/code-review#1429]
As we have a lot of issues in database, the admin panel is not able to run the SQL queries required in the 30s timeout.

This link will always fail https://api.code-review.moz.tools/admin/issues/issue/

We can simplify the requests by using select related & co

**Comment by EvaBardou** [comment]
Reopened as #1430 doesn't fix the issue, we're currently waiting for a bump to reproduce the error and further enhance performances.
