### ISSUE TITLE
Some documentation task do not build preview URLs

### ISSUE THREAD

**Issue by La0** [mozilla/code-review#1458]
Example on this revision https://phabricator.services.mozilla.com/D163141

![Screenshot 2022-12-07 at 10-51-16 ⚙ D163141 Bug 1792238 - Create a moz-button-group component r hjones](https://user-images.githubusercontent.com/101004/206146184-f7b1123d-e548-48b1-9d09-8178706f9704.png)

**Comment by marco-c** [comment]
I guess this is because the documentation wasn't actually touched. Perhaps by parsing the trees.json file we can improve the detection of changed documentation.

**Comment by marco-c** [comment]
> > I guess this is because the documentation wasn't actually touched. Perhaps by parsing the trees.json file we can improve the detection of changed documentation.
> 
> Good catch! Currently, we detect documentation files by [checking for the `docs` string inside their name](https://github.com/mozilla/code-review/blob/master/bot/code_review_bot/tasks/docupload.py#L80).
> 
> A quick fix for this issue could be to either skip commenting when `nb_docs` is equal to `0` or to send the previous "generic" comment as it was done before.
> 
> What would you prefer @marco-c?

Skipping when `nb_docs` is 0 sounds best to me, this way we don't needlessly say that documentation was changed when it actually wasn't.

> I was able to find instances of the new comment where it worked for 1 modified file [here](https://phabricator.services.mozilla.com/D163766#5382916) and [here](https://phabricator.services.mozilla.com/D162253#5390651), and also for several modified files [here](https://phabricator.services.mozilla.com/D163258#5389342).
> 
> But you're right, we need to improve the "documentation file" detection, because in the last link a `.py` configuration file was flagged as "documentation" even though it isn't. I don't know how we could better determine what's a documentation file, do you have any idea how to do that Marco?

We could filter by extension, only considering .rst and .md. Could you file a new issue about this, which is a linked but different problem?

**Comment by marco-c** [comment]
> Noted, will do. Would you like me to submit two distinct PRs too?

One PR is fine, preferably two commits, but one commit is fine too if it takes time to split the two changes
