### ISSUE TITLE
Set up Taskcluster so that it doesn't fail on pull requests from forks

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-review#146]

**Comment by La0** [comment]
It did work before: all my PRs are from my personal fork ([example last week](https://github.com/mozilla/code-review/pull/132))

**Comment by La0** [comment]
Seems to still work! my current PR #147  builds.

But is uses the [lowest priority](https://tools.taskcluster.net/groups/X7oQQjnHTr2zDbnH09GLiQ/tasks/bRpaROdpRG2b0c0AvD2lJQ/details).

**Comment by La0** [comment]
So it's pushes on the upstream repo that fail

**Comment by marco-c** [comment]
> But is uses the lowest priority.

Previous tasks also had "lowest" priority, so nothing changed there.

> So it's pushes on the upstream repo that fail

No, in my case the PR from a upstream branch worked (https://github.com/mozilla/code-review/pull/145), a PR from a branch in my fork didn't work (https://github.com/mozilla/code-review/pull/142).

The situation is strange though.
In your PR from last week, from your fork, we had two events "pull-request" and "push". They both worked.
In my PR from today, from my fork, we had two events "pull-request" and "push". Only "pull-request" worked.
In my PR from today, from upstream, we had two events "pull-request" and "push". They both worked.
In your PR from today, from your fork, we had only one event "pull-request". It worked.

**Comment by marco-c** [comment]
I'm almost convinced that the issue is that the "push" event should not have been there at all in my PR from a branch in my fork.

**Comment by marco-c** [comment]
I figured it out. Taskcluster integration is enabled on my fork, not in your fork. The failing "push" was actually from my fork and not from the upstream repo. It's a weird behavior, but probably a Taskcluster bug.
