### ISSUE TITLE
Add #taskgraph-reviewers to list of reviewers when the tgdiff task runs and identifies the revision as risky

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-review#1475]
This way taskgraph reviewers have visibility into these kind of changes.

**Comment by La0** [comment]
`subscribers.add` on https://phabricator.services.mozilla.com/conduit/method/differential.revision.edit/

**Comment by marco-c** [comment]
https://phabricator.services.mozilla.com/tag/taskgraph-reviewers/ or https://phabricator.services.mozilla.com/project/profile/140/ is what we need to add.

Maybe instead of `subscribers.add` we will have to use `projects.add`.

We should confirm that people belonging to that group receive an email when the group is added to a revision.

**Comment by La0** [comment]
I made a quick test using libmozdata to edit a [revision with tgdiff](https://phabricator.services.mozilla.com/D170260) and set the group.

- Using `subscribers.add` I get the weirdest error `libmozdata.phabricator.ConduitError: Edges are not available for objects of type '????'!
`
- Using `projects.add` It seems to work 

![Screenshot 2023-02-23 at 21-10-02 ⚙ D170260 Bug 1799769 - Import the Firefox  deb packages to the product delivery APT repo r jlorenzo](https://user-images.githubusercontent.com/101004/221019180-ce771bbe-9268-4f69-8ee2-1174a8c8299d.png)

Sample code

```
from libmozdata.phabricator import PhabricatorAPI

api = PhabricatorAPI("PROD token here")

api.edit_revision("170260", [
    {
        "type": "projects.add",
        "value": ["taskgraph-reviewers", ]
    }
])

# simple edit_revision:
def edit_revision(self, revision_id, transactions):
    self.request("differential.revision.edit", objectIdentifier=revision_id, transactions=transactions)
```

@marco-c  We should simply check that the members of the group received an email

**Comment by marco-c** [comment]
@jmaher mentioned that he didn't get any notification, so `projects.add` is not working.
Maybe we should get the taskgraph-reviewers group first, and then `subscribers.add` all members of that group.

**Comment by marco-c** [comment]
Maybe we should just add taskgraph-reviewers to the reviewers list, might be easier and it's what we want in the end.

**Comment by marco-c** [comment]
The tgdiff task itself could implement a set of criteria and output a value telling the bot whether it should add taskgraph-reviewers to the reviewers list or not.

@La0 is there an API to add a blocking reviewer on a revision?

**Comment by La0** [comment]
I only see `reviewers.add` and `request-review` in the list : I'll try both

**Comment by La0** [comment]
When trying `reviewers.add` it raises a nicer exceptions:

```
libmozdata.phabricator.ConduitError: Validation errors:
  - Reviewer "taskgraph-reviewers" is not a valid object.
```

**Comment by jmaher** [comment]
it looks like it worked on https://phabricator.services.mozilla.com/D170260

**Comment by La0** [comment]
My patch in-tree [has landed on MC](https://hg.mozilla.org/mozilla-central/rev/86e797935cf1), so we should get tgdiff tasks with `summary.json` now.

We need a patch for `TaskGraphDiffTask` in the bot:
- add an empty list `extra_reviewers` in `BaseTask` 
- `TaskGraphDiffTask.load_artifacts` needs to load the content of `public/taskgraph/diffs/summary.json`, and parse it.
- if the `summary` value is `WARNING`, add `"taskgraph-reviewers"` to `self.extra_reviewers`
- pass down the extra reviewers to the phabricator publish method (all the way from the workflow `publish` task, same as issues, patches, notices...)
- in the `PhabricatorReporter`, add an extra step to add extra reviewers when they are set
