### ISSUE TITLE
performance-unnecessary-copy-initialization: Local copy is warned but it's necessary

### ISSUE THREAD

**Issue by masayuki-nakano** [mozilla/code-review#15]
https://phabricator.services.mozilla.com/D7579

I understand what you try to avoid. However, this is a special case.  `TabChild::SendStartPluginIME()` is an IPC method. Therefore, its argument for `WidgetKeyboardEvent` is marked as `const` automatically. However, the event is actually modified during sending to another process. Therefore, we need to copy it for avoiding the unnecessary modification. Can I avoid the warning with special comment or something?

**Comment by marco-c** [comment]
The checker is useful in general, even though it might have some false positives.
