### ISSUE TITLE
Remove Phabricator required IDs on Revision model

### ISSUE THREAD

**Issue by La0** [mozilla/code-review#1523]
This is a followup on #1522 

The bot cannot process all revisions from Mozilla Central as some of them (backouts) do not have the Phabricator revision comment in their description.

Right now, the backend require to know the associated revision on Phabricator (both numercial ID and internal PHID) to publish any issue.

We could make these fields nullable on `Revision` and add these fields:
- Primary key becomes a random UUID (from uuid4)
- nullable bugzilla ID (provided from HGMO by the bot)
- nullable mercurial hash (would only be provided for MC, as we have the `Diff` system for try)

This would also require to support all these fields on the endpoint to create new revisions.

**Comment by La0** [comment]
After a discussion with @vrigal as he is blocked for #1581 , failing to properly identify the revisions from Mozilla-Central to compare against, I think we should even go one step further and store in the backend the base & head repositories on he `Revision` model.

Currently we only store mercurial hashes on the `Diff` model, which works fine... if we **only consider try pushes**. In try pushes, the developer pushes multiple patches on a single phabricator revision, each of them get a unique mercurial hash on try.
But we never store the resulting mercurial hash on mozilla central, nor their base repository & revision (which was not needed until now).

Now to compare against mozilla-central revisions, we need to identify them properly, bringing mercurial hashes on the `Revision` model.

The `Revision` would then have:
- required foreign key `base_repository` towards `Repository`
- required foreign key `head_repository` towards `Repository`
- required string `base_revision`
- nullable string `head_revision` (we do not know it for try pushes !)

All these informations would be provided by parsing the gecko decision task definition environment variables (`GECKO_HEAD_REF`, ...) and would allow us to easily find all the issues on a known mercurial hash.

Here is how the fields would be populated in the cases of a try push and a Mozilla-central ingested revision:

| Field           | Try push              | MC revision |
|-----------------|-----------------------|-------------|
| base_repository | MC or autoland or ... | MC          |
| head_repository | try                   | MC          |
| base_revision   | Y                     | Y           |
| head_revision   | X                     | null        |

Finally we need to think about data migration: we can find common cases (probably all cases) and upgrade them from a single data migration:
- all revisions on MC or autoland or unified with some `Diff` are from try
- all revisions on MC without any `Diff` are recent mozilla-central ingestions
- all revisions on NSS are coming from NSS-try
- ... is there any other case ?

Regarding mercurial hashes, we can generate dummy ones during the data migration, just to pass constraints, then run a django command to retrieve that information from phabricator & hgmo.
I'm not sure it's useful for try pushes (as they won't be compared against), but it should be done properly for all MC ingested tasks.

**Comment by marco-c** [comment]
Sounds good to me, it will be much clearer to have all the info.
One small suggestion: let's use a clear nomenclature so we don't get confused whenever we use the word "revision" (is it a Mercurial revision? Is it a Phabricator revision?). We could use revision for Phabricator and changeset or commit for Mercurial.

**Comment by vrigal** [comment]
I used `Revision.{base,head}_changeset` instead of `Revision.{base,head}_revision`, so it is clear that it is a reference to Mercurial.

**Comment by La0** [comment]
I was able to get some stats about number of revisions & diffs byb repositories used on a recent prod dump (thanks @abpostelnicu !).

This sql query:
```sql
select rev_repo.slug as rev_repo, diff_repo.slug as diff_repo, stats.nb_revisions, stats.nb_diffs
from (
	select rev.repository_id as rev_repo,
				 diff.repository_id as diff_repo,
				 count(rev.id) as nb_revisions,
				 count(diff.id) as nb_diffs
	from issues_revision as rev
	left join issues_diff as diff on (diff.revision_id = rev.id)
	group by rev.repository_id, diff.repository_id
) as stats
inner join issues_repository as rev_repo on (rev_repo.id = stats.rev_repo)
left join issues_repository as diff_repo on (diff_repo.id = stats.diff_repo)
order by stats.nb_revisions desc, stats.nb_diffs desc
```

provided the following results

|      rev_repo     |      diff_repo       | nb_revisions | nb_diffs |
| ------------------|----------------------|--------------|----------|
|  mozilla-central  | try                  |       241036 |   241036 |
|  mozilla-central  | autoland             |        53786 |    53786 |
|  mozilla-unified  | try                  |        37980 |    37980 |
|  mozilla-unified  | autoland             |         7953 |     7953 |
|  pine             | try                  |         2823 |     2823 |
|  ci-configuration | ci-configuration-try |         1244 |     1244 |
|  nss              | nss-try              |          933 |      933 |
|  taskgraph        | taskgraph-try        |          374 |      374 |
|  ci-admin         | ci-admin-try         |          126 |      126 |
|  pine             | autoland             |           11 |       11 |
|  mozilla-central  |                      |            8 |        0 |
|  mozilla-central  | nss-try              |            1 |        1 |
|  pine             |                      |            1 |        0 |

So we only have a few revisions without any diffs (recent mozilla-central ingestion), this means the data migration can be down to 2 queries:
1. all revisions without any diff get their head repo & base repo as `revision.repository_id`
2. all revisions with any diff should get :
   - base repo = `revision.repository_id`
   - head repo = `diff.repository_id`

This only works if all revisions with diffs have the same repo over all diffs:

```sql
select stats.revision_id, count(*)
from (
	select diff.revision_id, diff.repository_id, count(id)
	from issues_diff as diff
	group by diff.revision_id, diff.repository_id
) as stats
group by stats.revision_id
having count(*) > 1
```

This query gives us 52351 revisions where we have at least 2 different repositories.

After looking more closely into these results, I found out it's **exclusively** try & autoland repositories:
- there are no revisions with 3 repositories
- if we exclude `autoland`, we only have [1 really weird remaining revision](https://api.code-review.moz.tools/admin/issues/revision/55386/change/) (based on MC, diffs on try... and a last diff on nss-try).
   - We should delete `Diff 213608` from the database as it makes no sense.

In the end, the data migration is:
1. all revisions without any diff get their head repo & base repo as `revision.repository_id`
2. all revisions with any diff **excluding diffs with autoland repo** should get :
   - base repo = `revision.repository_id`
   - head repo = `diff.repository_id`

**Comment by La0** [comment]
We can now make the data migration to make Revision phabricator IDs (both ID & phid) optional.
