### ISSUE TITLE
Make a default task parser

### ISSUE THREAD

**Issue by gmierz** [mozilla/code-review#153]
Currently, all reviewbot tasks are parsed based their [suite type](https://github.com/mozilla/code-review/blob/master/bot/code_review_bot/workflow.py#L278-L302). Given that a default analysis format [exists](https://github.com/mozilla/code-review/blob/master/docs/analysis_format.md), we should have a default task parser as well (similar to `MozLintTask`).

Without this, the mozlint test type definitions (in taskcluster) will start to get messy since we have to add non-linting related tasks to it (or the other existing source-tests) to get them to run in reviewbot.

**Comment by marco-c** [comment]
Makes sense to me. We can have a default task parser to fallback to.
