### ISSUE TITLE
code review fails to run: code-review::general: WARNING: A generic error occurred in the code review bot.

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/code-review#1554]
3/3 phabricator revisions from today which I opened had the following message:

```
code-review::general: WARNING: A generic error occurred in the code review bot.
```

Log: https://phabricator.services.mozilla.com/D170278

@abpostelnicu

**Comment by marco-c** [comment]
I performed a migration of the DB today (from Postgres 11 to 14) and had to put the Heroku app on maintenance mode for a few hours.
It should be working again now.
