### ISSUE TITLE
Sentry: Missing issue hash, cannot publish on backend

### ISSUE THREAD

**Issue by abpostelnicu** [mozilla/code-review#1577]
This is a high yield warning on [Sentry](https://mozilla.sentry.io/issues/3573824888/?alert_rule_id=12607839&alert_timestamp=1677589615658&alert_type=email&environment=production&project=6273985).
This seems to be an issue with the current path for the issue that is used, `.`.

**Comment by La0** [comment]
I confirm this is happening for `.` paths when rustfmt find a global issue on the repo ([example](https://firefox-ci-tc.services.mozilla.com/tasks/RTtWGHF-TF-S1chIJYcDSQ/runs/0/logs/public/logs/live.log)).

```
[task 2024-10-05T21:08:36.427Z] TEST-UNEXPECTED-WARNING | /builds/worker/checkouts/gecko/:0 | Reformat rust (rust)
```

We can simply skip issues with path `.` in `BackendAPI.publish_issues`, right before checking their hash

**Comment by marco-c** [comment]
I guess rustfmt always reports this whenever there is at least one issue in the repo?

We should skip this specifically for rustfmt, so we don't risk hiding something by always ignoring ".".
