### ISSUE TITLE
Set the repository of the revision to try when ingesting try pushes

### ISSUE THREAD

**Issue by vrigal** [mozilla/code-review#1580]
Actually, the code review bot look for the Phabricator diff matching the try task, then retrieve a repository matching `revisionPHID` from Phabricator (which returns mozilla-central repository).
The repository is always set `mozilla-central` on revisions, making it impossible to differentiate issues related to try pushes or mozilla-central ingestions.

This is required to do #1541 (with #1579), otherwise the default revision used by the backend to filter known issues will always be the just created revision of the current analyzed try push.

**Comment by La0** [comment]
I think this is a part of #1523

**Comment by La0** [comment]
We are definetly doing that in #1523
