### ISSUE TITLE
bugprone-multiple-statement-macro: will cause a lot of issues

### ISSUE THREAD

**Issue by sylvestre** [mozilla/code-review#16]
**Phabricator URL:** https://phabricator.services.mozilla.com/D7665#176696

**Problem:**
This isn't the developer fault. So, not sure we should show that.
Maybe we should fix the issue directly in the header or silent this warning.

**Comment by marco-c** [comment]
This was fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1496379.
