### ISSUE TITLE
Code review bot always reports failure for comm-central reviews

### ISSUE THREAD

**Issue by jfx2006** [mozilla/code-review#1625]
I can't say for sure how long this hasn't worked right; perhaps it never did?

The code-review jobs run as expected, but even when all tests complete successfully, a message appears in the Phabricator review: 
```Broken: WARNING: A generic error occurred in the code review bot.```
For example, submitted earlier today: [D173902](https://phabricator.services.mozilla.com/D173902) - [try-c-c run](https://treeherder.mozilla.org/jobs?repo=try-comm-central&revision=8ca5b6ded678b8c2f065cf082983679adf4d935f) - All tests succeeded.

Another data point:
I don't see any data related to these runs on http://code-review.moz.tools/. comm-central and try-comm-central do not appear in the "Filter by Repository" drop down, and searching by revision or diff id returns no results. I watched the API requests to the backend in devtools and saw that  https://api.code-review.moz.tools/v1/repository/ does not include comm-central/try-c-c. 

I do see entries for comm-central on the tasks tab of code-review.moz.tools, they all say "unknown error".

I suspect a data step was missed when we initially set up code-review for comm-central.

**Comment by La0** [comment]
I created both repositories on the code review backend (comm-central & try-comm-central).

Following revisions should show up :crossed_fingers:

**Comment by marco-c** [comment]
@jfx2006 is it working OK now?

**Comment by jfx2006** [comment]
> @jfx2006 is it working OK now?

Yes, it is working now. Thanks for the quick fix!
