### ISSUE TITLE
 code-review-bot is still sending a default `python-requests` User Agent

### ISSUE THREAD

**Issue by globau** [mozilla/code-review#1696]
#1692 is marked as fixed, however we're still seeing `python-requests` user-agent requests from the bot.

Andi says this might be via the bot's usage of libmozdata.

I'd argue it's a bug that libmozdata doesn't require consumers to an application specific user-agent, but that's a different issue.

**Comment by marco-c** [comment]
#1698 updated libmozdata to the latest version, which contains https://github.com/mozilla/libmozdata/pull/219.

By default, libmozdata is using "libmozdata" as default user agent (https://github.com/mozilla/libmozdata/blob/aa80079c9a036531606942e175a25400fa69cfe3/libmozdata/connection.py#L57) for almost everything. I filed https://github.com/mozilla/libmozdata/issues/222 to enforce users of the lib setting the user agent. And I filed https://github.com/mozilla/libmozdata/issues/223 to use the user agent everywhere in libmozdata.

We can close this once those https://github.com/mozilla/libmozdata/issues/223 is fixed and we make a new release.

**Comment by marco-c** [comment]
https://github.com/mozilla/libmozdata/issues/223 was fixed, https://github.com/mozilla/code-review/pull/2394 and https://github.com/mozilla/code-review/pull/2395 will update libmozdata and mostly fix this.
Only https://github.com/mozilla/code-review/issues/2391 will be left after that.

**Comment by La0** [comment]
@mlbonhomme will fix these 2 dependabot MRs to land libmozdata update

**Comment by marco-c** [comment]
Fixed by 3d3e0424c9f3bf52d2b3dc640cf7f12183c13658 and 734bdaf0cf6f15f17c873d166a45e13499482269.
