### ISSUE TITLE
Problem with an automated review: spurious complaints about `noexcept`

### ISSUE THREAD

**Issue by jld** [mozilla/code-review#17]
**Phabricator URL:** https://phabricator.services.mozilla.com/D8943#308407

**Problem:** The bot complains that C++ move constructors should be declared `noexcept`, but the Firefox codebase is always compiled without exception support (and as far as I know there are no plans to ever change this), so the suggested change is unnecessary.

**Comment by abpostelnicu** [comment]
This is no longer the case so closing it.
