### ISSUE TITLE
Don't report issues when a new diff is available

### ISSUE THREAD

**Issue by indygreg** [mozilla/code-review#18]
On https://phabricator.services.mozilla.com/D13814 reviewbot commented on a lint failure on the initial diff submitted to Phabricator. However, the comment was left *after* I uploaded a new diff with the lint fixed (I spotted the lint failure in a Try run and "beat" reviewbot to the fix).

We may want to consider having reviewbot not comment on a differential revision if a newer diff has been uploaded.

**Comment by La0** [comment]
Now that we use lint result, this is fixed.
