### ISSUE TITLE
Update the cleanup DB script

### ISSUE THREAD

**Issue by abpostelnicu** [mozilla/code-review#1883]
Right now, the db cleanup script must be updated since it doesn't work anymore, there are references to the new table that was added, issuelink.
Surprisingly looking other the DB logs, for the past 4 months, this script was never ran on prod environment, so this adds the question how was the prod environment cleaned up the first time.

**Comment by marco-c** [comment]
Once we fix the cleanup script, we should also schedule it on cron (#1539).
