### ISSUE TITLE
Enable local Mercurial clones to build issue hashes

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-review#2194]
Depends on #2193 or, ideally, https://mozilla-hub.atlassian.net/browse/OPST-766.

**Comment by La0** [comment]
This is running in production since last week

**Comment by marco-c** [comment]
We can call this complete.

**Comment by La0** [comment]
Sure I can do that

**Comment by La0** [comment]
I made the fxci-config patch : https://github.com/mozilla-releng/fxci-config/pull/159

**Comment by La0** [comment]
The patch has been merged and deployed.

The [prod hook configuration](https://firefox-ci-tc.services.mozilla.com/hooks/project-relman/code-review-production) now has cache setup.

Sample [task](https://firefox-ci-tc.services.mozilla.com/tasks/ATKKnbQ7T6q3talAY-lbSQ/runs/0/logs/live/public/logs/live.log)
