### ISSUE TITLE
Check if we are able to trigger bugbug's hook

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-review#223]
I can't be sure yet, but I believe https://github.com/mozilla/code-review/blob/6c8ae784ef23b0ff3a7cb5a66788bf8133260e5f/events/code_review_events/workflow.py#L167-L171 will fail, as bugbug is in community-tc and code-review in firefox-ci.

**Comment by La0** [comment]
Yeah, i don't see how it can work, except if we store firefox-ci credentials in the community-tc secret...

**Comment by marco-c** [comment]
> Yeah, i don't see how it can work, except if we store community-tc credentials in the firefox-ci secret...

We can do this I guess, it shouldn't be too hard.

> The good solution is to move risk-analysis events into its own bugbug sub-project, using libmozevent. The project would then live in community-ci alongside the rest of bugbug.

It depends on how we intend to integrate the risk analysis results on Phab in the future. If it's going to be a different build on Phab, it could be totally separate from the current bot. Otherwise, it's going to have to be linked somehow.
One possibility could be to make the "classify patch" a API of the bugbug server, so the code review bot doesn't have to trigger the hook.

**Comment by La0** [comment]
The same phab build plan can have multiple HTTP notifications, hence triggering multiple backends.

**Comment by marco-c** [comment]
> The same phab build plan can have multiple HTTP notifications, hence triggering multiple backends.

That's another possibility, but it would still have the problem that the code review bot would not know of the risk analysis result.

**Comment by La0** [comment]
The classify patch should push its result in the backend.

**Comment by marco-c** [comment]
That's another possibility. Let's discuss all our options in the next few days and decide on the way forward.
(for now we can just fix the current behavior by using community-tc from firefox-ci)

**Comment by La0** [comment]
I created 2 clients on the community-ci instance:
- [project/relman/bugbug/code-review-testing](https://community-tc.services.mozilla.com/auth/clients/project%2Frelman%2Fbugbug%2Fcode-review-testing)
- [project/relman/bugbug/code-review-production](https://community-tc.services.mozilla.com/auth/clients/project%2Frelman%2Fbugbug%2Fcode-review-production)

Both clients simply have the scope `hooks:trigger-hook:project-relman/bugbug-classify-patch`

**Comment by La0** [comment]
[And requested the changes in Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1593749#c18)

**Comment by marco-c** [comment]
Things are working now, e.g. https://community-tc.services.mozilla.com/tasks/Cdrk0eYHToOI21CsEPIXFw.
