### ISSUE TITLE
land dependency updates

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/code-review#2259]

**Comment by La0** [comment]
I merged a few of them (easy ones).
The big items are:
- Django from 4.2 => 5.0
- Vue js major bump (2 => 3)
- Python version in docker images (from 3.11 to 3.12)

**Comment by La0** [comment]
The vue.js migration will be tracked in #2392 as it's a larger effort

**Comment by marco-c** [comment]
> The vue.js migration will be tracked in #2392 as it's a larger effort

Let's call this one fixed then.
