### ISSUE TITLE
Use pytest tmpdir in mock_config

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-review#23]
Instead of using the tempfile package at https://github.com/mozilla/release-services/blob/549691a0365854fe0c9e03c01728b7f66d7cbe9b/src/staticanalysis/bot/tests/conftest.py#L47, we can use the tmp_path or tmpdir fixture from pytest.

**Comment by La0** [comment]
This is already done, as mock_settings [does not need a temporary directory anymore](https://github.com/mozilla/code-review/blob/1.1.5/bot/tests/conftest.py#L41)
