### ISSUE TITLE
source-test-mozlint-license errors ignored

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-review#237]
https://phabricator.services.mozilla.com/D48565 triggered https://phabricator.services.mozilla.com/harbormaster/build/201460/ and https://treeherder.mozilla.org/#/jobs?repo=try&revision=70f0979c7f5f70801d52ff68c2413642aed617f0&selectedJob=276199903.

There are some `license` errors, which were not reported by the bot on Phabricator.

Later on, the patch landed (https://hg.mozilla.org/integration/autoland/rev/915910348bceea4cf865693859da04efabb12d22, https://treeherder.mozilla.org/#/jobs?repo=autoland&revision=915910348bceea4cf865693859da04efabb12d22) and was backed out because of the `license` failures (https://hg.mozilla.org/integration/autoland/rev/2fe825d522b2dd34a5f97bbae9d2aa251540123e, https://treeherder.mozilla.org/#/jobs?repo=autoland&revision=2fe825d522b2dd34a5f97bbae9d2aa251540123e).

**Comment by marco-c** [comment]
(infer was broken on this particular push, I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1596456 about that)

**Comment by La0** [comment]
Copied the revision on phab-dev as https://phabricator-dev.allizom.org/D1541

**Comment by La0** [comment]
Got the issue: the licence checks report full file issues at line 0. Which kinda makes sense as the licence declaration should be the very first line in the file.

I'm making a patch to consider this a full file issue

**Comment by La0** [comment]
Filed [Bug 1596704](https://bugzilla.mozilla.org/show_bug.cgi?id=1596704) to fix the analyzer

**Comment by marco-c** [comment]
This was fixed.
