### ISSUE TITLE
Publish some issues as unignorable lint issues and others as comments

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-review#25]
Issues that would break mozilla-central CI can be published as Phabricator lint issues (since they *have to* be fixed in order to land the revision).
Issues coming from SA tools with false positives should be published as comments, so that developers can decide to ignore them.

**Comment by marco-c** [comment]
@smacleod could we prevent landing patches which have unignorable lint issues?

**Comment by marco-c** [comment]
As we discussed recently, we could add a warning to Lando (or even prevent landing completely for unignorable issues, since they will lead to backout if landed).

**Comment by marco-c** [comment]
https://github.com/mozilla/code-review/pull/418 is publishing some errors as lint issues. After we release it to prod and after a few days of usage, we can go all the way and publish all errors as lint issues (see https://github.com/mozilla/code-review/pull/418#discussion_r364714241).

**Comment by marco-c** [comment]
Reopened for https://github.com/mozilla/code-review/issues/25#issuecomment-572570606, to track publishing all errors as lint issues.

**Comment by La0** [comment]
I'm adding a TC secret switch to enable/disable error publication, and will publish all errors as lint results.
