### ISSUE TITLE
Don't analyze wptsync patches

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-review#250]
They already submit them to try to make sure that everything is OK, so it's not worth for us to analyze them again (especially since they are huge stacks and we submit one push per patch in the stack!).

**Comment by La0** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1597314 yesterday. Do
you want to implement a filter in events ?

**Comment by marco-c** [comment]
Yeah, this way we also avoid applying the patches and pushing so many times.

With https://bugzilla.mozilla.org/show_bug.cgi?id=1597314 we'd just avoid running the source-test-* tasks (I don't know if we should do that).

**Comment by La0** [comment]
As discussed during the Engflow sync meeting, let's add a black list filter, that will be used by events:

In secret:
```
user_blacklist:
  - wptsync
```
When events start, it must retrieve these users PHID using `user.search` with `constraints={"usernames": [...]}`

Then in the top level workflow, when the build becomes public, we just check if the `revision.authorPHID` is in the list of black listed users, log the skipping and continue processing builds.

Note: there is no **search_users** method in the libmozdata phab client, but we could use directly a request (not sure it's worth it to map a function for that).

**Comment by marco-c** [comment]
The implementation plan sounds good to me.

> Note: there is no search_users method in the libmozdata phab client, but we could use directly a request (not sure it's worth it to map a function for that).

We have a `load_user` function (we are using it in libmozevent: https://github.com/mozilla/libmozevent/blob/87fa64a66c7289eee16660ccbc37152779382fbc/libmozevent/phabricator.py#L174), but without support for custom constraints. Since we already have that function, it's worth adding support for custom constraints and not duplicate the code.

**Comment by La0** [comment]
We should release after #260 is merged
