### ISSUE TITLE
Repeated/duplicate review for already-dropped issues

### ISSUE THREAD

**Issue by squelart** [mozilla/code-review#3]
**MozReview URL:** https://reviewboard.mozilla.org/r/174110/#review192572

**Problem:** The exact same issue was already reported just above ( https://reviewboard.mozilla.org/r/174110/#review192124 ), but I decided to "drop" it then, so it would be great if SSA could recognize that and not comment again.

**Comment by La0** [comment]
We now use Lint results on Phabricator so this is fixed.
