### ISSUE TITLE
Pass --warnings into mozlint

### ISSUE THREAD

**Issue by Pike** [mozilla/code-review#32]
We added `--warnings` to mozlint in #1447, but that got dropped again with the move to try.

Is this the right tracker to ask for it to be added back?

CC @flodolo, @ahal

**Comment by Pike** [comment]
Any update to this?

**Comment by sylvestre** [comment]
Not yet, we are still planning the work on the before/after (two pass mode), we will do it then.

@Pike is that blocking you now? Maybe we could do a temp workaround (I didn't ask @La0 so, maybe it will be too hard)

**Comment by La0** [comment]
We could do the env part now: 
1. adding an environment variable through `try_task_config.json`
2. checking that environment variable in mozlint

@sylvestre There would be at least one side effect: that would enable `rustfmt` reports as they are only warnings for now.

**Comment by sylvestre** [comment]
> @sylvestre There would be at least one side effect: that would enable `rustfmt` reports as they are only warnings for now.

This is something we could fix, probably not a blocker!

**Comment by flodolo** [comment]
Any update on this?

**Comment by sylvestre** [comment]
Sorry for the latency. @La0 @marco-c and myself worked on a plan for the 2 (or 3) phases analysis. We agreed on the strategy. 
The implementation should arrive in Q4.

@flodolo @Pike Maybe a dumb suggestion but what about changing mozlint to make your lint an error and not a warning anymore?

**Comment by flodolo** [comment]
> @flodolo @Pike Maybe a dumb suggestion but what about changing mozlint to make your lint an error and not a warning anymore?

In some cases these warnings are not blocker, and I'm not sure landing a patch with such failures would be ideal.

**Comment by sylvestre** [comment]
> In some cases these warnings are not blocker,

Are you able to automatically differentiate blocker from non blocker or it requires an human intervention?

**Comment by Pike** [comment]
Actually, this is about conflicting strings between patches and gecko-strings.

That's often a mishap, but sometimes the actual intent.

Which is why we want something that's annotating on phab, but green on autoland/central.

**Comment by sylvestre** [comment]
ok, for my culture, do you have some examples ? :)

We are not ignoring you, we are working on improving the analysis (2 phases analysis) which is a prereq for this issue.

**Comment by flodolo** [comment]
These two would have raised warnings, but the change without new ID is actually wanted
https://phabricator.services.mozilla.com/D50045
https://phabricator.services.mozilla.com/D49109

This one restores a string that was removed in mozilla-central, but it's still available in gecko-strings
https://phabricator.services.mozilla.com/D50088

The same patch, but with a changed message `cfr-doorhanger-extension-notification = Something New`, would have been an error.

**Comment by marco-c** [comment]
We should be able to do this now that we have warnings and errors.

**Comment by La0** [comment]
An easy target would be to do that for rustfmt only. It's a lower traffic analyzer, that outputs Rust diffs as warnings (we currently have never reported a `rustfmt` issue).

We could:
1. add an environment variable in the try_task_config
2. enable `--warnings` for rustfmt when that variable is set
3. support mozlint diffs #31 
4. run in testing
5. run in prod

If we are happy on that analyzer, make it global to all mozlint checks.

**Comment by La0** [comment]
Landed the env variable https://hg.mozilla.org/integration/autoland/rev/8f658b71a3c4

I'm gonna make a patch to enable warnings on l10n

**Comment by La0** [comment]
Turns out l10n is already active on reviewbot [with warnings](https://searchfox.org/mozilla-central/source/taskcluster/ci/source-test/mozlint.yml#259) and [reporting issues](https://phabricator.services.mozilla.com/D59634#1818107) so i'll stick to rustfmt.

**Comment by La0** [comment]
[The rustfmt patch is landing](https://bugzilla.mozilla.org/show_bug.cgi?id=1609116), i completely forgot that part with all hands & HR stuff...

**Comment by La0** [comment]
It landed: https://hg.mozilla.org/mozilla-central/rev/a6428fee77a9

**Comment by marco-c** [comment]
Once we verify all is good with rustfmt, we should enable it for all mozlint. Basically, changing https://hg.mozilla.org/mozilla-central/rev/a6428fee77a9#l1.14 to `if os.environ.get('CODE_REVIEW') == '1':` and removing the `code_review_warnings` config.

**Comment by marco-c** [comment]
I think it's time to do this!

**Comment by marco-c** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1703664
