### ISSUE TITLE
Handle better "private" revisions

### ISSUE THREAD

**Issue by La0** [mozilla/code-review#328]
1. Wait a bit more
2. Try to push a unit result on phabricator to warn the user

**Comment by sylvestre** [comment]
That happened here:
https://phabricator.services.mozilla.com/D55798

**Comment by sylvestre** [comment]
Another idea: if private, we retry in X minutes (5?) after in case it became open

**Comment by marco-c** [comment]
> Another idea: if private, we retry in X minutes (5?) after in case it became open

We already do this, retrying every 10 seconds for 5 times (so ~1 minute). We could increase the number of retries (maybe making it exponential so we don't retry too often) to get to a total of 3, 4, or 5 minutes.

**Comment by La0** [comment]
> maybe making it exponential so we don't retry too often

I'll need the help of a mathematician for that. Thank you @calixteman for taking this issue.

**Comment by La0** [comment]
We can use tenacity with exponential backoff

**Comment by marco-c** [comment]
We'll need to update libmozevent to make use of https://github.com/mozilla/libmozevent/pull/57.

**Comment by La0** [comment]
:arrow_right: https://github.com/mozilla/code-review/pull/465
