### ISSUE TITLE
Drop old routes from hooks

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-review#333]
We can remove:
- index:insert-task:project.releng.services.project.testing.static_analysis_bot.* and index:insert-task:project.releng.services.project.production.static_analysis_bot.*
- index:insert-task:project.relman.tasks.* and index:insert-task:project.releng.services.tasks.*, given https://github.com/mozilla/libmozevent/commit/c6cb2d818967ed0f9178f64ac83fa8a4dbb90c64

**Comment by La0** [comment]
Bad auto close

**Comment by La0** [comment]
Release 1.1.1 removed the old routes still used, and [this ci-configuration patch](https://phabricator.services.mozilla.com/D57289) removed all the extra scopes: we're clean !
