### ISSUE TITLE
Trigger a try run and patch in Phabricator on a dependency release

### ISSUE THREAD

**Issue by calixteman** [mozilla/code-review#342]
The idea is basically the following (dump_syms is an example here):
 - make a new release of dump_syms (git tag...)
 - then trigger a try run with updated revision similar to: https://treeherder.mozilla.org/#/jobs?repo=try&revision=519bbf974191d71af789daa4eea5385d175fafd9&selectedJob=280006976
 - and in the same time push a patch in Phabricator with updated revision, a link to the try job and with some default reviewers (or a group of).
It's a kind of dependabot to avoid to forget (or postpone for ever) to use the new release in firefox.
All this stuff could be triggered by the dependency itself on a particular action (git tag or whatever).

**Comment by marco-c** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1618282
