### ISSUE TITLE
Report issues new for revision

### ISSUE THREAD

**Issue by La0** [mozilla/code-review#363]
The backend now provides the `new_for_revision` information, we can use in a simple heuristic:

- on the first known diff, stick to current in_patch detection
- on followup diffs, report only new_to_revision issues

**Comment by marco-c** [comment]
> on followup diffs, report only new_to_revision issues

We should report both in_patch and new_to_revision, if we don't report in_patch we might miss some issues (e.g. if the developer doesn't fix an issue in the first iteration of the patch).

**Comment by vrigal** [comment]
@marco-c maybe you are thinking about this : #1373 ?

**Comment by marco-c** [comment]
Yes, thanks!
