### ISSUE TITLE
Detect never broken analyzers

### ISSUE THREAD

**Issue by La0** [mozilla/code-review#364]
Some analyzers on mozilla-central (tier 1) cannot break: they should always be fully green.
So any issue found by that analyzer should be reported.

We need to:
- mark those analyzers in the taskgraph (add something in their `extra` section)
- read that marker in the bot, and post every issue without filtering

**Comment by La0** [comment]
Current plan discussed with Marco on IRC:
1. Mozilla-Central analyzers switch to our format #180 
2. add a field *per issue* to specify how to report that issue, this will also solve the `mozlint --warnings` #32
3. react accordingly in the bot

**Comment by marco-c** [comment]
This is also a dependency of #25.

**Comment by La0** [comment]
Clear winner of #360 backouts list... First priority for next cycle

**Comment by La0** [comment]
The tier level is already availabe in the treeherder tasks extra payload, i'm using that to mark issues as "breaking CI" and should always be reported.

**Comment by marco-c** [comment]
We can start with that, but I'd go with the other option in the long run (marking the importance in the payload) so we can also support #32.

**Comment by La0** [comment]
Next steps would be :

1. Always publish errors on Phabricator - supporting issues outside of the patch as lint 
2. display errors & warnings clearly on the frontend

**Comment by marco-c** [comment]
This is done.
