### ISSUE TITLE
Display in patch & publication state in frontend

### ISSUE THREAD

**Issue by sylvestre** [mozilla/code-review#375]
https://code-review.moz.tools/#/stats
all Published are = 0

**Comment by abpostelnicu** [comment]
This  is strange, there are published issues though, take this for example: https://phabricator.services.mozilla.com/D37689#1777928

**Comment by La0** [comment]
The backend does not yet know how many issues are published, as I am not done with before/after.

Issues are still being published with "in patch" heuristic, everything works as before the frontend switch.

**Comment by La0** [comment]
- [ ] Store in patch status reported by backend
- [ ] Serve it through the API
- [ ] Display it through the frontend
