### ISSUE TITLE
Support unit test results

### ISSUE THREAD

**Issue by La0** [mozilla/code-review#41]
In order to support unit tests reporting through the code-review workflow, the bot needs to publish unit tests failures on Phabricator.
This is needed for [Bug 1561292](https://bugzilla.mozilla.org/show_bug.cgi?id=1561292)

Here is a proposal for a JSON artifact payload for unit tests: 

```json
{
  "path/to/test/file.py": [
    {
      "type": "unittest",
      "name": "AdditionTest",
      "result": "fail",
      "engine": "pytest",
      "details": "1+1 should be equal to 2, not 3",
    }
  ],
}
```

The result field should [match Phabricator](https://phabricator-dev.allizom.org/conduit/method/harbormaster.sendmessage/) : 

* pass
* fail
* skip
* broken
* unsound

**Comment by marco-c** [comment]
It might be worth resorting to parsing the logs, like other CI-related projects do. This way we don't have to implement the JSON output for all mozilla-central jobs.

**Comment by La0** [comment]
We would still need to define a standard file format, even for logs, in order to support multiple repositories.

**Comment by jasonLaster** [comment]
Here's the debugger test definition:
https://searchfox.org/mozilla-central/source/taskcluster/ci/source-test/node.yml#36-58



Here are some test failures:

- https://treeherder.mozilla.org/#/jobs?repo=try&revision=72731b78c3b692be10b506186c1c973819faf8e5&selectedJob=285984612
- https://treeherder.mozilla.org/#/jobs?repo=try&revision=0b068c78c6396d2e73a0dd5e4d6558517a5275c1&selectedJob=286594132
- https://treeherder.mozilla.org/#/jobs?repo=try&revision=5e6118bec7505b018e106b6f4967ba01999c9dc9&selectedJob=285661747

**Comment by La0** [comment]
Thanks Jason, i'll add a whitelist to allow publication of your unit tests results in Phabricator

**Comment by marco-c** [comment]
For reporting the failure, we can do it as we're doing for tests triggered by bugbug (https://github.com/mozilla/code-review/blob/c5d675a7f73f09ced3c787234c49c9fcb4109494/events/code_review_events/bugbug_utils.py#L359) and just report the failure with its treeherder URL (and in the future maybe put the failure summary too, getting it from treeherder, see #313)
