### ISSUE TITLE
In the test results, show the actual message

### ISSUE THREAD

**Issue by sylvestre** [mozilla/code-review#450]
Message == Code here:
![image](https://user-images.githubusercontent.com/733326/73594259-0b9dbe00-450d-11ea-9155-dd0c2910feb2.png)
It should probably be the actual error:
![image](https://user-images.githubusercontent.com/733326/73594274-2ec86d80-450d-11ea-880e-e54bc0f4bf08.png)

Found here:
https://phabricator.services.mozilla.com/D61394#C2104971NL2

**Comment by La0** [comment]
That would modify badly the output of the issue in the patch.
Phabricator does not display the description of the issue in the summary as
it can be pretty long.



Le sam. 1 févr. 2020 à 16:09, Sylvestre Ledru <notifications@github.com> a
écrit :

**Comment by La0** [comment]
This is done since 1.2.0
