### ISSUE TITLE
In Phabricator comment, add a link to the section with the error/warning

### ISSUE THREAD

**Issue by sylvestre** [mozilla/code-review#451]
In the comment:
![image](https://user-images.githubusercontent.com/733326/73594343-eeb5ba80-450d-11ea-9246-e19ec0e56a5c.png)
we could add a link here "Code analysis found 1 defect in the diff 223788:" (for example on _1 defect_) to go directly in the diff detail section:

![image](https://user-images.githubusercontent.com/733326/73594341-e52c5280-450d-11ea-967f-08deaab59006.png)

Example
https://phabricator.services.mozilla.com/D61394#UQ0_2

**Comment by marco-c** [comment]
The comment should also point to the right diff.

**Comment by marco-c** [comment]
We are now linking to the right diff, but not directly to the diff details section within the diff page (it isn't linkable).
