### ISSUE TITLE
Support hg.mozilla.org/ci projects

### ISSUE THREAD

**Issue by La0** [mozilla/code-review#461]
A simple configuration secret should be enough to cover the 3 projects

**Comment by La0** [comment]
I was able to clone ci-configuration on testing with a single ssh key (using #469), but now i've found a blocker: we need to support generic detection of decision tasks & their mercurial information.

Instead of maintaining a list of decision images in the bot, I can find the top parent in the tasks lists, starting from the current task (from code-review-issues up to decision task)

I can also generalize the list of environment keys to find mercurial revision & repos, but we'll certainly have to maintain that list somewhere (either in code or in the secret)

**Comment by marco-c** [comment]
I don't know if it's a rule, but usually the decision task has the same ID as the task group.

**Comment by La0** [comment]
Well that makes sense, as it's the first task to run. The issue is that you technically *can* specify a [different taskgroupid](https://community-tc.services.mozilla.com/api/queue/v1/task/PfpsObfySoi2B5xWk3STDQ) when creating a task

**Comment by La0** [comment]
Both issues are now solved in the code base, i'm [updating testing](https://community-tc.services.mozilla.com/tasks/groups/cd1r_B6wSxWkGPWtDxJufg).

**Comment by La0** [comment]
Events & bot seem fine on testing, i just requested to enable all CI projects available on phab-dev to test the full workflow: https://bugzilla.mozilla.org/show_bug.cgi?id=1616567

**Comment by La0** [comment]
All CI projects are now enabled on phabricator-dev + our testing environment.

**Comment by La0** [comment]
Current state on testing, when pushing a patch on phabricator-dev:
- events receive the notifications from phabricator-dev and is able to publish on the correct try instance
- a valid treeherder link is published on phabricator-dev (had to update the conf with `try_name`)
- i'm trying to trigger the code-review ending task on taskgraph, but i'm locked due to missing route scopes: [decision task is failing)(https://firefox-ci-tc.services.mozilla.com/tasks/JMcJz35mRNi9r_IuUgZbzQ/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FJMcJz35mRNi9r_IuUgZbzQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log) & [scopes request](https://phabricator.services.mozilla.com/D63449)
- i've created the repository on the backend through the admin interface

Once i get the scopes, the bot should be triggered and will post a task failure [on that bad patch](https://phabricator-dev.allizom.org/D1709) & issues should be saved in the backend.
Finally, i'll submit a clean patch to taskgraph to enable code-review ending task... and will also do that for the 2 other repositories

**Comment by La0** [comment]
The scopes are set, [the taskgraph decision task triggered code-review-issues](https://firefox-ci-tc.services.mozilla.com/tasks/S0O-TcddSXGb1z9XFH9DjA) and the bot started.
[But it failed to fetch the revision...](https://my.papertrailapp.com/systems/1233810f8ebb/events?focus=1167104651414360075&selected=1167104651414360075) need to investigate later on

**Comment by La0** [comment]
The taskgraph decision task does not embed the try syntax file content, so we do not have the Phabricator build...

We could either:
- Lookup the try_task_config.json on HGMO and read it ourselves from the bot
- Store the build id in the backend, starting from events

**Comment by marco-c** [comment]
Maybe we could put the build ID in the commit message? It would be a generic way to support all repos

**Comment by marco-c** [comment]
> Store the build id in the backend, starting from events

Or this, which might be useful also for #468

**Comment by La0** [comment]
For the commit message it's basically the same as reading HGMO.

I think we would benefit a lot more from doing the backend implementation, but that would be for next release.

**Comment by marco-c** [comment]
> For the commit message it's basically the same as reading HGMO.

Yep, but more generic (as not all repos have a try_task_config.json file).

**Comment by La0** [comment]
I just updated the production environment to 1.1.6 : Events now uses a single ssh key and clones all 3 CI projects.
Taskgraph will now have auto try pushes on phab prod.

**Comment by La0** [comment]
I updated the testing environment with the latest code from `master`, and triggered a build with a bad patch on taskgraph (on phab-dev) : [it works nicely](https://phabricator-dev.allizom.org/D1709) as the repo now supports cleanly the code review setup

**Comment by La0** [comment]
It's now working with release 1.1.7 in production. 
Here is a sample taskgraph bad patch with a report from the bot: https://phabricator.services.mozilla.com/D64938

I'm closing this issue as the work on our side is done, more should come from the projects side.
I'll file an issue about documentation & next steps on our side.
