### ISSUE TITLE
Enable responses automatically for all tests

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-review#49]
We can use pytest-responses to do this.

**Comment by Adrian-Tamas** [comment]
Hi, although I am newish to python, I would like to help with this issue. Can you please detail what needs to be done other than adding pytest-responses in the dependencies and ensure that the unit tests still work or fix failing ones?

**Comment by La0** [comment]
Hello @Adrian-Tamas ,

Adding the `pytest-responses` dep in `bot/requirements-dev.txt`, then removing the `responses.activate` calls should be enough.

To run the tests you'll then need to run `pytest` and check that every test passes.

**Comment by Adrian-Tamas** [comment]
Thanks for the quick reply. I will look into this
