### ISSUE TITLE
shipit_static_analysis: modernize-raw-string-literal should be suggested only on longer string

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/code-review#5]
**MozReview URL:** https://reviewboard.mozilla.org/r/192754/#review197914

**Problem:** From [Bug 1411480 comment 28](https://bugzilla.mozilla.org/show_bug.cgi?id=1411480#c28):

> > Warning: Escaped string literal can be written as a raw string literal
> > [clang-tidy: modernize-raw-string-literal]
> > 
> >   aResult.AssignLiteral("\"");
> >                         ^
> >                         R"(")"
> 
> Jerome: I personally don't find this warning helpful. While raw string literals can be useful -- particularly if you have a long string literal that would require many escaped chars -- I think it's misguided to say that they are universally preferable to normal string literals. And this example is one case where I think raw string literals are less clear.
> 
> Is it possible to change the static analysis so it only makes this suggestion if the number of escaped chars exceeds a threshold, say 3 or 4?

**Comment by sylvestre** [comment]
It has been more than a year and afaik, nobody complained again about that, I think we can close it.
