### ISSUE TITLE
Configure default task trigger from secret, by repository

### ISSUE THREAD

**Issue by La0** [mozilla/code-review#502]
In order to support tasks without the default artifact, but with task failure detection, we need to be able to filter the tasks by name (we always use `source-test-` prefix for MC and others).

For example, taskgraph would need a filter like `tests-*`.
This filtre should be configurable on the `repositories` secret, and default to `*`

**Comment by marco-c** [comment]
What if we considered all tasks in the group?

**Comment by La0** [comment]
That's of course easier if we just use the **dependant** tasks in the group.
We should just check if we avoid the build tasks on mozilla-central (we should as they are not dependant)
