### ISSUE TITLE
Publish build errors as lint results

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-review#552]
When we can parse a build error and point to the file where the build error is, we could use a lint issue instead of a unit test result.

**Comment by marco-c** [comment]
@abpostelnicu do you know how easy/difficult it would be to parse the build error?

**Comment by abpostelnicu** [comment]
Started something similar in #558, so in order to better understand this we want the build error to be also published as lint results?

**Comment by marco-c** [comment]
> Started something similar in #558, so in order to better understand this we want the build error to be also published as lint results?

I'd say we could publish it just as a LintResult, so it's reported on the "bad" line
