### ISSUE TITLE
Add a comment when errors are published outside of patch

### ISSUE THREAD

**Issue by La0** [mozilla/code-review#553]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1610715#c6

When we publish errors outside of patch, developers can be confused why they are reported.
We should add an extra info in the summary comment: ` Code analysis found X defects in the diff Y (defects might be in the parent stack)` in such a case

**Comment by marco-c** [comment]
It'd be nice to avoid reporting issues that are in a parent patch, as they are already reported in the parent patch. I wonder if we could list issues from the parent and skip them. Or maybe somehow do a try push which considers only the latest patch.

**Comment by junngo** [comment]
I submitted PR :)
Please let me know if there is anything that needs to be modified.

**Comment by bhushan-borole** [comment]
Hello, I would like to work on this issue.

**Comment by marco-c** [comment]
@junngo submitted a PR to fix this a while ago, https://github.com/mozilla/code-review/pull/561, though it seems it's been stuck for a while.
@junngo do you still want to continue or do you want @bhushan-borole to take over?

**Comment by junngo** [comment]
Hello @marco-c 
I think @bhushan-borole can take this issue.

**Comment by bhushan-borole** [comment]
Thats great @junngo.
I will start working on it @marco-c
