### ISSUE TITLE
Display clang-format patches in lint message

### ISSUE THREAD

**Issue by La0** [mozilla/code-review#564]
Now that the bot support merging several neighboring clang-format issues, it should be possible to build the resulting file, and display it to developers, so they can simply copy/paste it

**Comment by marco-c** [comment]
Fixed by 21eb7f9, GitHub forgot to close this.

**Comment by marco-c** [comment]
Ah, it hasn't been merged yet, that's why :P

**Comment by marco-c** [comment]
Fixed by f7c292fab40bc01264b0fb3df39f5a635d6da636.
