### ISSUE TITLE
Move Python requirements version on top files

### ISSUE THREAD

**Issue by La0** [mozilla/code-review#65]
They are currently set on requirements_frozen.txt only, which is not used by CI nor setup scripts.

We should:
1. use the versions from `requirements_frozen.txt` on the top requirements files
2. remove `requirements_frozen.txt`
3. let dependabot do its thing

**Comment by marco-c** [comment]
We need to do the same in code-coverage.

**Comment by La0** [comment]
already filed an issue

**Comment by La0** [comment]
Done in #66
