### ISSUE TITLE
Do not download hgmo files unless their are part of the revision - performance improvement? 

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla/code-review#743]
Just judging from the log output I experienced earlier today, it seems like a lot of work (and latency) could be avoided, if files wouldn't be downloaded if they aren't part of the revision under test.

> 2020-10-16 08:06:04.232341 [INFO    ] code_review_bot.revisions: Downloading HGMO file (url='https://hg.mozilla.org/try/raw-file/a563afcc89d72ebcb55faafdedb425e79d225b43/mfbt/WeakPtr.h')
> 2020-10-16 08:06:07.654214 [WARNING ] code_review_bot.revisions: Issue path is not in revision (path='mfbt/WeakPtr.h' revision=PHID-DIFF-kni5auvw36ssciyfikhy)

**Comment by marco-c** [comment]
We are doing this because some analyzers could find issues that are outside the files of the revision (e.g. coverity). The plan was to do https://github.com/mozilla/code-review/issues/553.

**Comment by mozfreddyb** [comment]
Makes sense. Feel free to close :)
