### ISSUE TITLE
Problem with an automated review (modernize-use-equals-default)

### ISSUE THREAD

**Issue by tomrittervg** [mozilla/code-review#8]
**MozReview URL:** https://reviewboard.mozilla.org/r/214140/#review230054

**Problem:**

Warning is: Use '= default' to define a trivial default constructor [clang-tidy: modernize-use-equals-default]

The code is

```
LRUCache() {
  this->cache.SetLength(LRU_CACHE_SIZE);
}
```

so I don't understand why it thinks it is a trivial constructor...

**Comment by abpostelnicu** [comment]
This issue no longer happens.
