### ISSUE TITLE
Ignore exceptions from the backend

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-review#983]
Currently a backend exception can cause a total failure of the bot (e.g. it happened in https://phabricator.services.mozilla.com/D126393).
We should instead ignore backend errors, as they are not really blocking the bot from working.

https://github.com/mozilla/code-review/blob/71390ca1bf455fde5db4b34dc271307edf5bb955/bot/code_review_bot/backend.py#L135 raises, goes back to https://github.com/mozilla/code-review/blob/71390ca1bf455fde5db4b34dc271307edf5bb955/bot/code_review_bot/workflow.py#L290, goes back to https://github.com/mozilla/code-review/blob/71390ca1bf455fde5db4b34dc271307edf5bb955/bot/code_review_bot/workflow.py#L96, exception caught in https://github.com/mozilla/code-review/blob/71390ca1bf455fde5db4b34dc271307edf5bb955/bot/code_review_bot/cli.py#L165

**Comment by abpostelnicu** [comment]
Maybe we shouldn't raise an exception and just log an error message. It's not like `backend` is crucial for the running of the bot.

**Comment by marco-c** [comment]
Agreed

**Comment by marco-c** [comment]
We can either catch backend_api exceptions in workflow.py, or stop throwing exceptions in the BackendAPI class
