### ISSUE TITLE
Backend is failing with `pine` revisions

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-review#985]
We should figure it out and fix it.

**Comment by abpostelnicu** [comment]
Let's first get a workaround for #983 and then we can work on this, wdyt?

**Comment by abpostelnicu** [comment]
It was a db issue, now it should be fixed.

**Comment by marco-c** [comment]
We had to add Pine to the DB.

**Comment by marco-c** [comment]
I filed #988 to document this better.
